global using System.Net.WebSockets;
global using System.Text;
global using System;
global using Newtonsoft.Json;
global using PCA.Core.Domain;
global using System.Collections.Generic;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;