global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Text.Json.Nodes;
global using Microsoft.Extensions.Hosting;
global using PCA.Core.Services;
global using PCA.Core.Domain;